name: Build

on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Build wheel
        run: python setup.py bdist_wheel --universal

      - name: Upload Python wheel
        uses: actions/upload-artifact@v2
        with:
          name: Python wheel
          path: ${{github.workspace}}/dist/livermask-*.whl
          if-no-files-found: error

  test:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      # max-parallel: 10
      matrix:
        os: [ windows-2019, ubuntu-20.04, macos-11 ]
        python-version: [ 3.7 ]

    steps:
      - uses: actions/checkout@v1
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: "Python wheel"

      - name: Install wheel
        if: runner.os == 'Windows'
        run: |
              $TARGET = Resolve-Path "${{github.workspace}}/livermask-*.whl" | Select -ExpandProperty Path
              echo $TARGET
              pip install --find-links=${{github.workspace}} $TARGET

      - name: Install wheel
        if: runner.os != 'Windows'
        run: pip install --find-links=${{github.workspace}} livermask-*.whl

      - name: Test CLI
        run: livermask --help

      - name: Download test sample
        run: |
          pip install gdown==4.4.0
          mkdir samples
          mkdir results
          cd samples
          gdown https://drive.google.com/uc?id=1shjSrFjS4PHE5sTku30PZTLPZpGu24o3
          gdown https://drive.google.com/uc?id=1bNmls5o0Rxw5HvBF1IYnEzmpysYJaywN

      - name: Test inference .nii
        run: |
          livermask --input samples --output results --verbose --vessels

      - name: Test inference .nii.gz
        run: |
          livermask --input samples --output results --verbose --vessels --extension .nii.gz

  conda:
    needs: build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-2019, ubuntu-20.04 ] #, macos-11 ]
        python-version: [ 3.7 ]
    steps:
      - uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.7

      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: "Python wheel"

      - name: Install wheel
        if: runner.os == 'Windows'
        run: |
              $TARGET = Resolve-Path "${{github.workspace}}/livermask-*.whl" | Select -ExpandProperty Path
              echo $TARGET
              pip3 install --find-links=${{github.workspace}} $TARGET

      - name: Install wheel
        if: runner.os != 'Windows'
        run: pip3 install --find-links=${{github.workspace}} livermask-*.whl

      - name: Download test sample
        run: |
          pip3 install gdown==4.4.0
          mkdir samples
          mkdir results
          cd samples
          gdown https://drive.google.com/uc?id=1shjSrFjS4PHE5sTku30PZTLPZpGu24o3
          gdown https://drive.google.com/uc?id=1bNmls5o0Rxw5HvBF1IYnEzmpysYJaywN

      - name: Test inference
        run: |
          livermask --input samples --output results --verbose --vessels
