name: Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-18.04
            TARGET: ubuntu
            CMD_BUILD: pip install git+https://github.com/andreped/livermask.git

          - os: macos-10.15
            TARGET: macos
            CMD_BUILD: pip install git+https://github.com/andreped/livermask.git

          - os: windows-2019
            TARGET: windows
            CMD_BUILD: pip install git+https://github.com/andreped/livermask.git
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python 3.7
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install dependencies
        run: pip install wheel setuptools

      - name: Build wheel
        run: |
          python setup.py bdist_wheel --universal
          ls

      - name: Install program for ${{matrix.TARGET}}
        run: ${{matrix.CMD_BUILD}}

      - name: Test CLI
        run: livermask --help
